spring.application.name=FCPT
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DB_NAME}
pdf.service.url=${PDF_SERVICE}